name: Code Analysis

on:
  push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  code_analysis_composer:
    name: ${{ matrix.actions.name }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']

        actions:
          -   name: ECS
              run: 'composer test:style'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - run: ${{ matrix.actions.run }}
